// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8qJzWAtqNJlgONVKDa3dt34Yj9gYlTMo',
    appId: '1:1094257976263:web:45adf0e187267223a86fe2',
    messagingSenderId: '1094257976263',
    projectId: 'skv-admin',
    authDomain: 'skv-admin.firebaseapp.com',
    storageBucket: 'skv-admin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5PvZ0gEEwcSHov-f2GpQSPNqTtjcT2hY',
    appId: '1:1094257976263:android:2ce666f3ceafebdda86fe2',
    messagingSenderId: '1094257976263',
    projectId: 'skv-admin',
    storageBucket: 'skv-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-Xoofd-fjox8EXzBvAN1xQCW3r1TC4M',
    appId: '1:1094257976263:ios:85c7d0bab800cd45a86fe2',
    messagingSenderId: '1094257976263',
    projectId: 'skv-admin',
    storageBucket: 'skv-admin.firebasestorage.app',
    iosBundleId: 'com.example.skvWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr-Xoofd-fjox8EXzBvAN1xQCW3r1TC4M',
    appId: '1:1094257976263:ios:85c7d0bab800cd45a86fe2',
    messagingSenderId: '1094257976263',
    projectId: 'skv-admin',
    storageBucket: 'skv-admin.firebasestorage.app',
    iosBundleId: 'com.example.skvWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8qJzWAtqNJlgONVKDa3dt34Yj9gYlTMo',
    appId: '1:1094257976263:web:dd44f5fb88d795f2a86fe2',
    messagingSenderId: '1094257976263',
    projectId: 'skv-admin',
    authDomain: 'skv-admin.firebaseapp.com',
    storageBucket: 'skv-admin.firebasestorage.app',
  );
}
